[build]
  # Disable Hugo; publish a static placeholder directory
  command = ""
  publish = "netlify"

[build.environment]
  PYTHON_VERSION = "3.13"

# Optionally add headers for caching static assets
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=600"


